colnamesdf <- read.table("./UCI HAR Dataset/features.txt",header = FALSE)
colnames <- as.vector(colnamesdf[,2])
xtestdf <- read.table("./UCI HAR Dataset/test/X_test.txt",header = FALSE)
colnames(xtestdf) <- colnames
subtestdf <- read.table("./UCI HAR Dataset/test/subject_test.txt",header = FALSE)
colnames(subtestdf) <- c("Subject")
ytestdf <- read.table("./UCI HAR Dataset/test/y_test.txt",header = FALSE)
colnames(ytestdf) <- c("Activity")
testdf <- cbind(subtestdf,ytestdf,xtestdf)
xtraindf <- read.table("./UCI HAR Dataset/train/X_train.txt",header = FALSE)
colnames(xtraindf) <- colnames
subtraindf <- read.table("./UCI HAR Dataset/train/subject_train.txt",header = FALSE)
colnames(subtraindf) <- c("Subject")
ytraindf <- read.table("./UCI HAR Dataset/train/y_train.txt",header = FALSE)
colnames(ytraindf) <- c("Activity")
traindf <- cbind(subtraindf,ytraindf,xtraindf)
totdf <- rbind(testdf,traindf)
library(dplyr)
tstoutdf <- totdf[,grepl('Activity|Subject|-std|-mean',colnames(totdf))]
tstoutdf <- mutate(tstoutdf, ActivityName = factor(Activity, labels = c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING")))
library(reshape2)
meltdf <- melt(tstoutdf, id=c("Subject","ActivityName"), measure.vars = 3:81)
sumdf <- group_by(meltdf,Subject,ActivityName,variable)
datdf <- summarize(sumdf,avg=mean(value))
write.table(datdf,"tidydata.txt",row.name=FALSE)